
[general]
	#Minimum number of pursuing mobs to trigger a music sequence
	#Range: > 1
	minPursuitEntities = 2
	#Seconds without mobs around needed for music to stop itself.
	#Range: > 1
	decayTime = 20
	#Resource locations of sounds to play. Separate with commas.
	sounds = ["minecraft:music_disc.pigstep", "minecraft:music_disc.mellohi", "minecraft:music.th3_ost_skellige_battle_1", "minecraft:music.th3_ost_skellige_battle_2"]

