
[ingame]
	mining_autoswitch_items = ["justhammers:gold_hammer", "minecraft:air", "justhammers:diamond_reinforced_hammer", "minecraft:stone_shovel", "minecraft:wooden_shovel", "justhammers:iron_reinforced_impact_hammer", "minecraft:wooden_pickaxe", "cataclysm:tidal_claws", "justhammers:gold_reinforced_impact_hammer", "justhammers:iron_impact_hammer", "justhammers:netherite_hammer", "justhammers:stone_impact_hammer", "justhammers:netherite_reinforced_hammer", "minecraft:stone_axe", "justhammers:gold_destructor_hammer", "justhammers:gold_reinforced_hammer", "justhammers:stone_destructor_hammer", "cataclysm:black_steel_shovel", "minecraft:wooden_axe", "justhammers:diamond_reinforced_impact_hammer", "minecraft:diamond_pickaxe", "cataclysm:black_steel_pickaxe", "justhammers:iron_hammer", "minecraft:netherite_pickaxe", "justhammers:diamond_impact_hammer", "minecraft:golden_axe", "minecraft:netherite_axe", "justhammers:iron_reinforced_hammer", "justhammers:netherite_destructor_hammer", "minecraft:diamond_axe", "justhammers:stone_hammer", "justhammers:stone_reinforced_hammer", "minecraft:iron_shovel", "minecraft:iron_pickaxe", "minecraft:diamond_shovel", "cataclysm:black_steel_axe", "minecraft:stone_pickaxe", "justhammers:diamond_destructor_hammer", "justhammers:gold_impact_hammer", "justhammers:netherite_reinforced_impact_hammer", "minecraft:netherite_shovel", "minecraft:iron_axe", "justhammers:diamond_hammer", "justhammers:iron_destructor_hammer", "justhammers:stone_reinforced_impact_hammer", "justhammers:netherite_impact_hammer", "minecraft:golden_shovel", "minecraft:golden_pickaxe"]
	#Range: 1 ~ 10
	long_press_count = 2
	#Range: 0 ~ 30
	max_hit_projectiles = 30
	#Allowed Values: NONE, HURT, TARGET
	health_bar_show_option = "HURT"
	show_target_indicator = true
	filter_animation = false
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	enable_laser_pointer = true
	camera_auto_switch = false
	auto_preparation = false
	blood_effects = true
	no_mining_in_combat = true
	aiming_correction = true
	show_epicfight_attributes = true
	use_animation_shader = false
	first_person_model = true
	battle_autoswitch_items = ["irons_spellbooks:misery", "minecraft:wooden_sword", "epicfight:golden_spear", "dungeonnowloading:spawner_sword", "epicfight:uchigatana", "dungeonnowloading:life_stealer", "cataclysm:void_forge", "minecraft:netherite_sword", "wom:diamond_staff", "epicfight:bokken", "ef_weapon_extended:gold_knuckles", "wom:moonless", "wom:wooden_staff", "cataclysm:gauntlet_of_guard", "wom:iron_staff", "cataclysm:zweiender", "wom:agony", "cataclysm:wrath_of_the_desert", "epicfight:netherite_dagger", "wom:golden_greataxe", "wom:solar", "epicfight:diamond_greatsword", "wom:moonless_handle", "shifu_epic_fight_skill_recipe:dragon_fist", "wom:golden_staff", "minecraft:stone_sword", "cataclysm:cursed_bow", "epicfight:iron_tachi", "epicfight:golden_greatsword", "epicfight:iron_dagger", "cataclysm:ancient_spear", "irons_spellbooks:amethyst_rapier", "wom:antitheus", "ef_weapon_extended:diamond_knuckles", "minecraft:diamond_sword", "wom:solar_obscuridad", "epicfight:golden_dagger", "wom:satsujin_sheath", "wom:stone_staff", "epicfight:diamond_longsword", "wom:ender_blaster", "epicfight:diamond_spear", "epicfight:diamond_dagger", "epicfight:glove", "epicfight:netherite_longsword", "irons_spellbooks:keeper_flamberge", "epicfight:golden_tachi", "epicfight:iron_greatsword", "epicfight:iron_spear", "epicfight:golden_longsword", "irons_spellbooks:magehunter", "wom:herrscher", "irons_spellbooks:spellbreaker", "minecraft:air", "wom:diamond_greataxe", "cataclysm:coral_spear", "wom:gesetz_handle", "epicfight:stone_greatsword", "wom:gesetz", "cataclysm:gauntlet_of_bulwark", "cataclysm:infernal_forge", "cataclysm:black_steel_sword", "cataclysm:final_fractal", "shifu_epic_fight_skill_recipe:blazingfist", "wom:netherite_staff", "wom:netherite_greataxe", "irons_spellbooks:staff_of_the_nines", "bladeofolympus:blade_of_olympus", "cataclysm:khopesh", "minecraft:golden_sword", "cataclysm:the_incinerator", "cataclysm:coral_bardiche", "epicfight:netherite_tachi", "wom:satsujin", "epicfight:netherite_greatsword", "mca:scythe", "epicfight:diamond_tachi", "epicfight:iron_longsword", "epicfight:netherite_spear", "epicfight:stone_spear", "wom:iron_greataxe", "irons_spellbooks:claymore", "ef_weapon_extended:iron_knuckles", "minecraft:iron_sword", "cataclysm:athame", "wom:tormented_mind", "wom:ruine", "ef_weapon_extended:netherite_knuckles"]

	[ingame.ui]
		stamina_bar_x = 120
		stamina_bar_y = 10
		#Allowed Values: LEFT, RIGHT, CENTER
		stamina_bar_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		stamina_bar_y_base = "BOTTOM"
		weapon_innate_x = 42
		weapon_innate_y = 48
		#Allowed Values: LEFT, RIGHT, CENTER
		weapon_innate_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		weapon_innate_y_base = "BOTTOM"
		passives_x = 70
		passives_y = 36
		#Allowed Values: LEFT, RIGHT, CENTER
		passives_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		passives_y_base = "BOTTOM"
		#Allowed Values: HORIZONTAL, VERTICAL
		passives_align_direction = "HORIZONTAL"
		charging_bar_x = -119
		charging_bar_y = 60
		#Allowed Values: LEFT, RIGHT, CENTER
		charging_bar_x_base = "CENTER"
		#Allowed Values: TOP, BOTTOM, CENTER
		charging_bar_y_base = "CENTER"

